cityparkcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('parks/', views.ParkList.as_view(), name='parks'),
    path('parks/<int:park_id>', views.parks_detail, name='detail'),
    path('parks/create/', views.ParkCreate.as_view(), name='parks_create'),
    path('parks/<int:pk>/update/', views.ParkUpdate.as_view(), name='parks_update'),
    path('parks/<int:pk>/delete/', views.ParkDelete.as_view(), name='parks_delete'),

    path('parks/<int:park_id>/add_visit', views.add_visit, name='add_visit'),
    # ^^^ function view for visit creation
    # path('parks/<int:pk>/create_visit', views.VisitCreate.as_view(), name='visit_create'),
    #  ^^^ CBV for visit creation
    path('parks/<int:park_id>/add_photo', views.add_photo, name='add_photo'),

    path('parks/<int:park_id>/assoc_feature/<int:feature_id>/', views.assoc_feature, name='assoc_feature'),
    path('parks/<int:park_id>/unassoc_feature/<int:feature_id>/', views.unassoc_feature, name='unassoc_feature'),

    path('features/', views.FeatureList.as_view(), name='features_index'),
    path('features/<int:pk>/', views.FeatureDetail.as_view(), name='features_detail'),
    path('features/create/', views.FeatureCreate.as_view(), name='features_create'),
    path('features/<int:pk>/update/', views.FeatureUpdate.as_view(), name='features_update'),
    path('features/<int:pk>/delete/', views.FeatureDelete.as_view(), name='features_delete'),
    
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from datetime import date


class Feature(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('features_detail', kwargs={'pk': self.id})

class Park(models.Model):  
    name = models.CharField(max_length=100)
    neighborhood = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    features = models.ManyToManyField(Feature)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'park_id': self.id})

class Visit(models.Model):
    date = models.DateField('Date of Visit')
    comment = models.TextField(max_length=180, default='none')
    park = models.ForeignKey(Park, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.comment} on {self.date}"

    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    park = models.ForeignKey(Park, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for park_id: {self.park_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Visit

class VisitForm(ModelForm):
  class Meta:
    model = Visit
    fields = ['date', 'comment']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
import uuid
import boto3
from .models import Park, Feature, Photo
from .forms import VisitForm

S3_BASE_URL = 'https://s3.us-west-1.amazonaws.com/'
BUCKET = 'cityparkcollector-bucket'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('parks')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {
        'form': form, 
        'error_message': error_message
    }
    return render(request, 'registration/signup.html', context)

@login_required
def parks_index(request):
    # parks = Park.objects.all()
    # ^^^ this code will make all parks appear ^^^
    parks = Park.objects.filter(user=request.user)
    # ^^^ this code will make only the parks the user has created appear ^^^
    return render(request, 'parks/index.html', {'parks': parks})

@login_required
def parks_detail(request, park_id):
    park = Park.objects.get(id=park_id)
    features_park_doesnt_have = Feature.objects.exclude(id__in = park.features.all().values_list('id'))
    visit_form = VisitForm()
    return render(request, 'parks/detail.html', {
        'park': park,
        'visit_form': visit_form,
        'features': features_park_doesnt_have
    })

@login_required
def add_visit(request, park_id):
    form = VisitForm(request.POST)
    form.instance.user = request.user
    if form.is_valid():
        new_visit = form.save(commit=False)
        new_visit.park_id = park_id
        new_visit.save()
    return redirect(
        'detail', 
        park_id=park_id
    )

#  ^^^ function for create visit

# class VisitCreate(CreateView):
#     model = VisitForm
#     fields = '__all__'

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)

class ParkCreate(LoginRequiredMixin, CreateView):
    model = Park
    fields = ['name', 'neighborhood', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ParkUpdate(LoginRequiredMixin, UpdateView):
    model = Park
    fields = ['neighborhood', 'description']

class ParkDelete(LoginRequiredMixin, DeleteView):
    model = Park
    success_url = '/parks/'

class ParkList(LoginRequiredMixin, ListView):
    model = Park

@login_required
def assoc_feature(request, park_id, feature_id):
    Park.objects.get(id=park_id).features.add(feature_id)
    return redirect('detail', park_id=park_id)

@login_required
def unassoc_feature(request, park_id, feature_id):
    Park.objects.get(id=park_id).features.remove(feature_id)
    return redirect('detail', park_id=park_id)

class FeatureCreate(LoginRequiredMixin, CreateView):
    model = Feature
    fields = '__all__'
    success_url = '/features/'

class FeatureDetail(LoginRequiredMixin, DetailView):
    model = Feature

class FeatureList(LoginRequiredMixin, ListView):
    model = Feature

class FeatureUpdate(LoginRequiredMixin, UpdateView):
    model = Feature
    fields = ['name']

class FeatureDelete(LoginRequiredMixin, DeleteView):
    model = Feature
    success_url = '/features/'

@login_required
def add_photo(request, park_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, park_id=park_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', park_id=park_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the City Park Collector</h1>
    <hr />
    

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>CityParkCollector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CityParkCollector</a></li>
        </ul>
        <ul class="right">
          <!-- <li><a href="{% url 'about' %}">About</a></li>
       

          <li><a href="{% url 'parks_create' %}">Add a Park</a></li>
          <li><a href="{% url 'parks' %}">View All Parks</a></li>
          <li><a href="{% url 'features_create' %}">Add a Feature</a></li>
          <li><a href="{% url 'features_index' %}">View All Features</a></li>
        
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li> -->

       
        {% if user.is_authenticated %}
          <li><a href="{% url 'features_create' %}">Add a Feature</a></li>
          <li><a href="{% url 'features_index' %}">View All Features</a></li>
          <li><a href="{% url 'parks_create' %}">Add a Park</a></li>
          <li><a href="{% url 'parks' %}">View All Parks</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 CityParkCollector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h2>Visit city parks across Denver!</h2>
<h2>Record your favorite feature!</h2>

{% endblock %}

main_app/templates/main_app/feature_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Feature</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'features_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/feature_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Feature Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ feature.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'features_update' feature.id %}">Edit</a>
        <a href="{% url 'features_delete' feature.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/feature_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Feature</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/feature_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Feature List</h1>

{% for feature in feature_list %}
  <a href="{% url 'features_detail' feature.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ feature.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/park_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Park</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' park.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/park_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}

    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Park</h1>

{% endif %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/park_list.html
{% extends 'base.html' %}
{% block content %}

<h1>City Park List</h1>

{% for park in park_list %}
<a href="{% url 'detail' park.id %}">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ park.name }}</span>
        <p>Neighborhood: {{ park.neighborhood }}</p>
        <p>Description: {{ park.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/parks/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Park Details</h1>

<div class="row">

  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ park.name }}</span>
        <p>Neighborhood: {{ park.neighborhood }}</p>
        <p>Description: {{ park.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'parks_update' park.id %}">Edit</a>
        <a href="{% url 'parks_delete' park.id %}">Delete</a>
      </div>
    </div>
    
    {% for photo in park.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    <form action="{% url 'add_photo' park.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
    
  </div>
  <div class="col s6">

    <form action="{% url 'add_visit' park.id %}" method="post">
      {% csrf_token %}
      {{ visit_form.as_p }}
      <input type="submit" class="btn" value="Add Visit">
    </form>    
    <br>
    <table class="striped">
      <thead>
        <tr>
          <th>Visit Date</th>
          <th>Comment</th>
          <!-- <th>User</th> -->
        </tr>
      </thead>
      <tbody>
        {% for visit in park.visit_set.all %}
          <tr>
            <td>{{visit.date}}</td>
            <td>{{visit.comment}}</td>
            <!-- <td>{{request.user}}</td> -->
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ park.name }}'s features</h3>
    {% if park.features.count %}
      {% for feature in park.features.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ feature.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_feature' park.id feature.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No features :(</h5>
    {% endif %}
  </div>
 <!-- Available features will come after this line -->
 <div class="col s6">
  <h3>Potential features</h3>
  {% if features.count %}
    {% for feature in features.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ feature.name }}
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_feature' park.id feature.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{park.name}} Already Has All Features Available</h5>
  {% endif %}
</div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  // const selectEl = document.getElementById('id_feature');
  // M.FormSelect.init(selectEl);
</script>

  {% endblock %}

main_app/templates/parks/index.html
{% extends 'base.html' %}
{% block content %}

<h1>City Park List</h1>

{% for park in parks %}
<a href="{% url 'detail' park.id %}">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ park.name }}</span>
        <p>Neighborhood: {{ park.neighborhood }}</p>
        <p>Description: {{ park.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}